DROP DATABASE IF EXISTS adashop;

CREATE DATABASE IF NOT EXISTS adashop;

USE adashop;

CREATE TABLE IF NOT EXISTS tblKunde (
	p_kundenNr INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	kGebDat DATE,
	kNachname VARCHAR( 60 ) NOT NULL,
	kVorname VARCHAR( 40 ) NOT NULL,
	kStrasse VARCHAR( 60 ) NOT NULL,
	kPlz INT UNSIGNED NOT NULL,
	kOrt VARCHAR( 40 ) NOT NULL,
	kIban CHAR( 22 ) NOT NULL,
	kPasswort VARCHAR( 20 ) NOT NULL,
	kMail VARCHAR( 40 ) NOT NULL
);

CREATE TABLE IF NOT EXISTS tblBestellung (
	p_bstID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	bstZeit DATETIME NOT NULL,
	bstIstWarenkorb BOOL NOT NULL,
	bstGesamtsumme DECIMAL( 8,2 ),
	bstRabattsatz DECIMAL( 4,2 ),
	f_kundenNr INT UNSIGNED NOT NULL,
	FOREIGN KEY ( f_kundenNr ) REFERENCES tblKunde ( p_kundenNr )
);

CREATE TABLE IF NOT EXISTS tblZustand (
	p_zustID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	zustName VARCHAR( 20 ) NOT NULL
);

CREATE TABLE IF NOT EXISTS tblKategorie (
	p_katID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	katName VARCHAR( 25 ) NOT NULL
);

CREATE TABLE IF NOT EXISTS tblArtikel (
	p_artID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	artName VARCHAR( 60 ) NOT NULL,
	artBeschreibung TEXT,
	artBestand INT UNSIGNED NOT NULL,
	artPreis DECIMAL( 7,2 ) NOT NULL,
	f_zustID INT UNSIGNED NOT NULL,
	f_katID INT UNSIGNED NOT NULL,
	FOREIGN KEY ( f_zustID ) REFERENCES tblZustand ( p_zustID ),
	FOREIGN KEY ( f_katID ) REFERENCES tblKategorie ( p_katID )
);

CREATE TABLE IF NOT EXISTS tblBild (
	bildPfad VARCHAR( 255 ) NOT NULL,
	f_artID INT UNSIGNED NOT NULL,
	FOREIGN KEY ( f_artID ) REFERENCES tblArtikel ( p_artID )
);

CREATE TABLE IF NOT EXISTS tblBestellposition (
	f_bstID INT UNSIGNED NOT NULL,
	f_artID INT UNSIGNED NOT NULL,
	bposMenge INT UNSIGNED NOT NULL,
	FOREIGN KEY ( f_bstID ) REFERENCES tblBestellung ( p_bstID ),
	FOREIGN KEY ( f_artID ) REFERENCES tblArtikel ( p_artID )
);
